### ISSUE TITLE
Issue with pip download

### ISSUE THREAD

**Issue by alexander-alleman** [mjenior/riptide#1]
Following the pip download a syntax error is given after import is called: 

from riptide import *
Traceback (most recent call last):

  File "C:\Users\alexa\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-ad19cdbffa75>", line 1, in <module>
    from riptide import *

  File "C:\Users\alexa\anaconda3\lib\site-packages\riptide\__init__.py", line 3, in <module>
    from .riptide import *

  File "C:\Users\alexa\anaconda3\lib\site-packages\riptide\riptide.py", line 639
    def _constrain_and_analyze_model(model, coefficient_dict, fraction, sampling_depth, objective, tasks, minimum_threshold=1e-6, cpus):
                                    ^
SyntaxError: non-default argument follows default argument

___________________________
This line contains "cpus" which is not in the present GitHub version. 

After removing cpus or replacing riptide with github version import works fine . I think the GitHub / pip version need to be matched

**Comment by mjenior** [comment]
Hi Alexander,

Sorry for the delay, I've been busy with a another project and couldn't get to this right away. I was integrating that option for cpus since I found out that fva can sometimes fail on certain machines if that argument isn't handled correctly. Working on the issue now, and I'll let you know when the newest version is up.

**Comment by mjenior** [comment]
Version 2.9.3 should import correctly. Let me know if it works on you machine and I can close this issue.

**Comment by mjenior** [comment]
Tested and rolled out the final feature set, so I'm going to go ahead and close this issue.
