### ISSUE TITLE
Error: Something is wrong with the provided bounds nan and nan in constraint

### ISSUE THREAD

**Issue by mkulyashov** [mjenior/riptide#12]
Dear RIPTiDE team!

Our research group uses genome-scale metabolic modelling approach to investigate metabolic systems of pro- and eukarytic organisms. We have been working on the reconstruction and contextualization of GSM models based on omics data, in general, and transcriptomics data integration, in particular. To conduct this research we are using web-version of our original BioUML platform ([10.1093/nar/gkac286](https://doi.org/10.1093/nar/gkac286)) where we would like to harness the RiPTIDE tool developed by your team via corresponding Jupyter notebook. So we have an original transcriptomics dataset containing expression data for chicken embryos in several experimental conditions that we analyzed using Edger and DESeq2 tool. We were able to integrate the processed data provided by Edger tool into the model and run the context-specific GSM model for chicken recently published ([10.1371/journal.pone.0254270](https://doi.org/10.1371/journal.pone.0254270)), while the similar analyses for DESeq2 data was failed due to the error: "Something is wrong with the provided bounds nan and nan in constraint". We doublechecked the data in order to identify the issue with constraints and checked the format correctness of the file using an example from your github project. We would really appreciate if you could to help us with the issue or give us some clues or causes of the error?

**Comment by mjenior** [comment]
Hi, hanks for trying out riptide in your group! That looks like a cobrapy error I have seen sometimes when an incompatible variable is tried as reaction bound. Is it possible your normalization process introduced a non-numeric value somewhere in your transcript abundance table?

**Comment by mkulyashov** [comment]
Thank you very much for the advice. It has really happened and we were able to identify the error on this step. However, we have faced with another issue running contextualization of the model. The tool get back an error in regards to bounds of the biomass equation like: Something is wrong with the provided bounds nan and nan in constraint e86e0286-9ca3-11ed-8b43-0242ac140009: nan <= 1.0*BOF - 1.0*BOF_reverse_2629d <= nan. However, default lower and upper boundaries are standards: [0; 1000]. Moreover, we double-checked that the issue is related to the biomass equation (or its boundaries) by means changing the objective function on exchange reaction for CO2. The tool is running well in this casem, but R_BOF (biomass equation) was removed in outcome FBA distributions. Could you give us a hint or cause of the error?

**Comment by mjenior** [comment]
This issue pope often pretty often when multiple objectives or metabolic tasks are required. Since riptide prunes zero flux reactions, biomass is not really required for the model to generate CO2 in a parsimonious flux objective formulation. If you make sure your are updated to riptide v3.4.78, you can set the ID either BOF or CO2 as a tasks='' arg and it will force the solver to to maintain some amount of flux through that reaction, but to a smaller degree than whatever you have set as the objective. Let me know how that works for you.

**Comment by mkulyashov** [comment]
Thank you very much for the advices. they helped us. Now, all is working!
