### ISSUE TITLE
Issues of output results from riptide

### ISSUE THREAD

**Issue by Xingchen-Bian** [mjenior/riptide#2]
Dear Matt Jenior,

I'm using riptide for transcriptomic-constraint genome scale metabolic model. When I use different gene expression datasets, I got similar results, i.e. similar growth rate, flux distributions of each reactions. I do not know how to explain this.
The model information are as follows: The model was constructed using carveme with cplex as its solver (https://carveme.readthedocs.io/en/latest/usage.html ). I use this code: carve 163560.faa -g LB -i LB. The no constraint model has 1028 genes. The gene expression datasets are from control group (ctrl_4h) and antibiotic combination treatment group (comb_4h). There are 197/1028 differentially expressed genes (adjusted p value <0.05, fold change >2).
Here attached the bacteria genome annotation file 163560.faa (for model construction), the model LB163560 I've constructed, the gene expression data from two groups and output results from riptide.

I would be very grateful if you could help.
Thank you very much!

Best regards,
Xingchen Bian
[Attachments.zip](https://github.com/mjenior/riptide/files/7473172/Attachments.zip)

**Comment by mjenior** [comment]
This can sometimes happen for three main reasons; The first is that the transcriptomic datasets might just be really similar (doesn't look to be the case with your data). Alternatively, the media conditions you have constrained the model to may be too limiting to there to be any ability of RIPTiDe to find different patterns of use. And finally, the construction of the model itself may have errors like energy generating loops which will always be identified as the most efficient use of metabolism. The third issue can often happen with models fresh out of automated reconstruction. Hopefully that gives you some directions to go to troubleshoot your analysis.

**Comment by Xingchen-Bian** [comment]
Dear Matt Jenior,

Thanks a lot! That's really helpful!
Will check the draft model carefully.

Best regards,
Xingchen Bian
