### ISSUE TITLE
issues on samples and fraction

### ISSUE THREAD

**Issue by Xingchen-Bian** [mjenior/riptide#3]
Dear Matt Jenior,

I'm using riptide for transcriptomic-constraint genome scale metabolic model. When I set fraction to a higher value such as 0.9 with samples being the default value 500, I can not get 500 samples for each reaction in the result file. When I change the fration to a lower one i.e. 0.7, it works. How can it happen? 

I would be very grateful if you could help.
Thank you very much!

Best regards,
Xingchen Bian

**Comment by mjenior** [comment]
This tends to happen when solution space gets highly constrained based on the transcription coefficients and some of the samples are actually infeasible. Those samples are removed from the final table before it is returned to the user. Just like you said, the lower the fraction the less constrained the solutions are and more samples are feasible. You could potentially just increase the number of samples for the 0.9 minimum fraction sampling.
