### ISSUE TITLE
Error - 'symengine.lib.symengine_wrapper.Symbol' object has no attribute '_index'

### ISSUE THREAD

**Issue by akemedis** [mjenior/riptide#5]
Having trouble whilst pruning 0-flux subnetworks. 
Using python version 3.10.4

**Comment by mjenior-zymergen** [comment]
Looks like a dependency issue. You should try manually updating symengine.

**Comment by mjenior** [comment]
Since this has been dormant for a while, I'm going to go ahead and close this issue.
